### ISSUE TITLE
Position correction seems to be wrong sometimes.

### ISSUE THREAD

**Issue by AmonShokhinAhmed** [lizrad/recursio#98]
Players sometimes get corrected to positions very far away or positions that do not seem plausible.

**Comment by kb173** [comment]
During these corrections, there is a large lagspike on the server:

![image](https://user-images.githubusercontent.com/18697097/140626033-eb96ae9e-3ebc-4ef1-b3eb-cc15ca9102e7.png)

This is accompanied by a constant framerate decrease on the client:

![image](https://user-images.githubusercontent.com/18697097/140626042-0748eb91-fe43-4abc-8f58-5dd2c7496661.png)

It seems like that is caused by the MinimapIcon's pixel read for whatever reason - must be an underlying issue with the Viewport image, maybe a thread stall? https://github.com/lizrad/recursio/commit/d4b3ea9d3211e3aa773871136a136cb1f61df9bf commented out the MinimapIcon and it seems like that at least caused a significant improvement.

Two other take-aways from this:

1. The client can bombard the server with packets, stalling it and creating lagspikes for everyone (essentially a very easy DDoS attack). We need to find a way to prevent that.
2. The lagspike is mostly caused by the Ringbuffer. It's implemented pretty inefficiently - we could try to turn it into a static array rather than constantly dynamically resizing it, or even write a simple C++ module for it since it's so central and commonly used.
